mlflow:
  run_name: camelyon-ood-cls
  experiment_name: test0
data:
  batch_size: 128
  img_size: 96
  n_class: 2
  name: camelyon
  content_channels: 4
out_dir: ./out/camelyon
train:
  early_stopping_patience: 5
  early_stopping_mode: min
  epochs: 1
trainer_param:
  cls_lr: 0.0003
  channel_split:
  - 4
  - 8
vae:
  run_id: d9013201e20f475780f7429fa3e0587c
  model_name: best_model
cls_model:
  hidden_dim: 256
  out_dim: 2
